version: '4.1'
package:
  name: cirros-simple-cloud-init
  vendor: osm
  version: '0.1'
  maintainer: Name, Company, Contact
  description: Some description about this sample
descriptor_extension: yml
files:
- path: cirros_1vnf_nsd.yaml
  type: application/vnd.etsi.osm.nsd
  tags:
  - etsi.osm
- path: cirros_vnfd.yaml
  type: application/vnd.etsi.osm.vnfd
  tags:
  - file-ref:cloud_init/cloud-config.txt
  - etsi.osm
- path: cloud_init/cloud-config.txt
  type: text/x-shellscript
  tags:
  - etsi.osm
