---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "test-td-imp"
  version: "0.1"
  maintainer: "5GTANGO Test Team"
  description: "This is a integration test artifact."
files:
  - path: "test-descriptor.yml"
    type: "application/vnd.5gtango.nsd"
    tags:  # (optional)
      - "eu.5gtango"