---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "test-ns-nsid1v_osm"
  version: "0.1"
  maintainer: "5GTANGO Test Team"
  description: "This is a integration test artifact."
files:
  - path: "nsd.yaml"
    type: "application/vnd.etsi.osm.nsd"
    testing_tags:
      - "etsi.osm.testingtag.example"
  - path: "vnfd1.yaml"
    type: "application/vnd.etsi.osm.vnfd"
